site_name: Frig Docs
theme: readthedocs
repo_name: "GitHub"
repo_url: https://github.com/frig-js/frig/
site_dir: "dist"
pages:
- "Frig": index.md
- "Core Components": core_components.md
- "Input Types": input_types.md
- "Bootstrap": bootstrap.md
