site_name: Frig Docs
theme: readthedocs
repo_name: "GitHub"
repo_url: https://github.com/TouchBistro/frig/
extra_css:
- "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"
- "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"
- "css-symlinks/frigging-bootstrap.css"
extra_javascript:
- "https://fb.me/react-with-addons-0.13.3.js"
- "js-symlinks/frig.js"
- "js-symlinks/frigging-bootstrap.js"
- "js-symlinks/the-basics.js"
- "js-symlinks/two-way-data-binding.js"
pages:
- "Frig": index.md
- "Getting Started": getting_started.md
- "Components": components.md
